<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Your Order History (Sortable)</name>
   <tag></tag>
   <elementGuidId>6ead4f00-c96a-478d-8f23-053f0b0113a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.section-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='NextGenGadgets'])[1]/following::h2[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>3b00b64c-92bd-4d09-908f-52e99757315c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-title</value>
      <webElementGuid>e1d7d1d3-5ac0-4fbb-915a-9a829dbf2b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your Order History (Sortable)</value>
      <webElementGuid>01edb664-d799-4570-8d2b-25c39c145fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;orders-page&quot;]/main[@class=&quot;content-container&quot;]/h2[@class=&quot;section-title&quot;]</value>
      <webElementGuid>f7010d1a-2d32-48ea-9a68-aa7f3a861786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NextGenGadgets'])[1]/following::h2[1]</value>
      <webElementGuid>da8b1099-15d8-4346-a00a-3a928bdb2954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order ID'])[1]/preceding::h2[1]</value>
      <webElementGuid>919596a9-f157-4fdc-bbf8-0eacfd9b7cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Placed'])[1]/preceding::h2[1]</value>
      <webElementGuid>59e3d72b-606b-455f-98fb-6d92e122156a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your Order History (Sortable)']/parent::*</value>
      <webElementGuid>edf6cec3-6f1b-4c3e-ab23-441a0c268e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>f743f259-75ff-4a5d-ba7d-8564a4f7c51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Your Order History (Sortable)' or . = 'Your Order History (Sortable)')]</value>
      <webElementGuid>1679db70-7418-4435-8697-8e31ff74eff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
