<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_NextGenGadgets</name>
   <tag></tag>
   <elementGuidId>e1303c85-76f3-4572-a07a-2bbda31f681c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='main-header']/div/a/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;NextGenGadgets&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>570ba15b-29b0-4f1a-9053-88b9833ac377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>9653915e-8412-4f04-94ed-3c5ab5b2e3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NextGenGadgets</value>
      <webElementGuid>42cd8714-badb-4baa-a40c-71c0ae6123db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@id=&quot;main-header&quot;]/div[@class=&quot;header-content&quot;]/a[@class=&quot;logo-link&quot;]/h1[@class=&quot;logo&quot;]</value>
      <webElementGuid>15496445-bc32-4c25-8177-ba0b1e43ad3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='main-header']/div/a/h1</value>
      <webElementGuid>f967b01b-bbcf-44e4-a3ea-8d367afd119f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::h1[1]</value>
      <webElementGuid>84691500-1aa6-434f-8fc0-cd4a91d5b90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories'])[1]/preceding::h1[1]</value>
      <webElementGuid>c0dd2dc6-15ee-4482-8ca1-a392d68ab463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NextGenGadgets']/parent::*</value>
      <webElementGuid>7d602422-d41f-42ad-b7e7-c933f0d9434e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>cbb51428-b508-4031-94c8-ed1ee244b032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'NextGenGadgets' or . = 'NextGenGadgets')]</value>
      <webElementGuid>b385fb92-3f5a-4ae5-9874-8d2cbf8676d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
