<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Loading Date  Time</name>
   <tag></tag>
   <elementGuidId>e422f92d-0b09-462b-a88b-79a79e900f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#current-date-time</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='current-date-time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3feff094-688b-46e5-9a0c-638a19c01523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>current-date-time</value>
      <webElementGuid>9d63fe93-155e-46ac-a5e2-795dd1c19362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datetime-banner</value>
      <webElementGuid>945b534a-e400-47be-98f5-7249756f9d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loading Date &amp; Time...</value>
      <webElementGuid>8887712b-6573-48e1-bc5c-558c27e9bd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@id=&quot;main-header&quot;]/p[@id=&quot;current-date-time&quot;]</value>
      <webElementGuid>85375dc4-b6f5-4465-b0ed-c36a5930ae2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='current-date-time']</value>
      <webElementGuid>dffe0e1c-eda8-4c18-b945-7c5c69570b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='main-header']/p</value>
      <webElementGuid>adf7bede-8e4e-408e-8356-edb6f881a116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::p[1]</value>
      <webElementGuid>66e44319-b45e-4f63-b6e5-7e4e0556a44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[1]</value>
      <webElementGuid>24416892-b32a-48f9-8b2c-033f6cd4c82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Innovation at Your Fingertips'])[1]/preceding::p[1]</value>
      <webElementGuid>8f7a41ad-5e2b-40f6-baa0-5fc99fcb779e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore Deals'])[1]/preceding::p[2]</value>
      <webElementGuid>85db1757-f2f8-4016-a0fc-0cd0b3135336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Loading Date &amp; Time...']/parent::*</value>
      <webElementGuid>62583522-d6e4-4b41-becb-576bb8456659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>a0da488d-7e46-4572-886d-de57ccfa1571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'current-date-time' and (text() = 'Loading Date &amp; Time...' or . = 'Loading Date &amp; Time...')]</value>
      <webElementGuid>2b0f4284-7f34-436c-8237-3030f4950c1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
