<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Shipping                    FREE</name>
   <tag></tag>
   <elementGuidId>7cbfbead-591a-411d-938a-ce525c693f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='$4897.00'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3c4268d-c726-4088-a9c3-e6cdf8695e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>summary-line</value>
      <webElementGuid>13b3e037-dd93-4f51-a8eb-ba6d98fbb5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Shipping:
                    FREE
                </value>
      <webElementGuid>f5792878-0806-4577-b42d-56a256dc94e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cart-page&quot;]/main[@class=&quot;content-container&quot;]/div[@class=&quot;cart-content-wrapper&quot;]/div[@class=&quot;cart-summary-section&quot;]/div[@class=&quot;summary-line&quot;]</value>
      <webElementGuid>d54fa133-942f-4702-8e80-5d5867951a24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4897.00'])[1]/following::div[1]</value>
      <webElementGuid>b16af512-7f2c-4b67-a8a1-b8df93f3537d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>ddeaf991-0087-4cea-a574-5d6b669f3b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                    Shipping:
                    FREE
                ' or . = '
                    Shipping:
                    FREE
                ')]</value>
      <webElementGuid>54b6cab6-abca-4120-b1c3-e89e0e0b5c29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
