<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card Number_cardNumberIframe</name>
   <tag></tag>
   <elementGuidId>4ae9260a-c115-4039-a576-6be6ab401db2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardNumberIframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardNumberIframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6aa52762-bcc6-432c-966a-0f401f14b723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c575e3c-9658-43ae-9869-c567760ae178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardNumberIframe</value>
      <webElementGuid>55511af8-e68a-42da-9c8f-1cfb40bb59b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>XXXX XXXX XXXX XXXX</value>
      <webElementGuid>bdefc4c7-4280-440a-bb4a-e6dc72d8695a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[@id=&quot;secure-payment-form&quot;]/input[@id=&quot;cardNumberIframe&quot;]</value>
      <webElementGuid>8ea308ea-9454-4152-ba2d-347026c7eeb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardNumberIframe']</value>
      <webElementGuid>a036f2aa-f8c2-4935-9153-06661fa77faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='secure-payment-form']/input</value>
      <webElementGuid>1a6b8058-8656-472a-b227-9a044fd76a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4b3e147b-0f9f-402c-8f60-23a4283e0ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cardNumberIframe' and @placeholder = 'XXXX XXXX XXXX XXXX']</value>
      <webElementGuid>7dd9c3c6-074f-4b3f-910b-08c2f34c3d54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
