<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_reg-lastName</name>
   <tag></tag>
   <elementGuidId>723f29ca-349f-442f-a756-d1ac7ef69ba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reg-lastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg-lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Last Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c535f46-536a-4396-9af3-15ef28063a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>748740bc-3f64-40fa-8b7a-9cd75dddcc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg-lastName</value>
      <webElementGuid>edfe7c22-3edc-4830-a338-858c290ae562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;register-page&quot;]/main[1]/div[@class=&quot;auth-container&quot;]/form[@id=&quot;registration-form&quot;]/input[@id=&quot;reg-lastName&quot;]</value>
      <webElementGuid>39ac4c46-2fc2-42f7-899b-0aa3501d9ff6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg-lastName']</value>
      <webElementGuid>00f0a701-a5c9-4f6b-92ac-ff97b3eed3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration-form']/input[2]</value>
      <webElementGuid>4f85149d-03c5-4dbf-9f42-9b32bcbcbccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>27304442-daaa-437f-9f11-37775330ac38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'reg-lastName']</value>
      <webElementGuid>884d7e48-0edd-42a6-8fe6-d6b6949299ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
