<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_reg-email</name>
   <tag></tag>
   <elementGuidId>ba4c405b-285f-438a-8e66-79ce394857f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reg-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abb6a426-0611-4c74-a3a8-5dd34959d694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>cedbfa4a-4e1d-491e-82c7-26c24475f572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg-email</value>
      <webElementGuid>201aab1c-7d8d-4cb4-b5f2-33b78f61b8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;register-page&quot;]/main[1]/div[@class=&quot;auth-container&quot;]/form[@id=&quot;registration-form&quot;]/input[@id=&quot;reg-email&quot;]</value>
      <webElementGuid>0eaf6147-672f-425c-b81e-ac70f71fcc65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg-email']</value>
      <webElementGuid>47a16c07-dd95-4a92-9060-5050299830ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration-form']/input[3]</value>
      <webElementGuid>98cdbc1a-a548-4c70-9c47-75fea4856326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>fc01556a-15e3-473e-9755-1c3269aa0b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'reg-email']</value>
      <webElementGuid>009922a3-b2be-46ff-824f-cd49d6e77c69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
