<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_reg-firstName</name>
   <tag></tag>
   <elementGuidId>60518b0d-dc0c-4172-b820-681a6ec0f11e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reg-firstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg-firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99edcabd-2e95-4c42-a39f-ae97df4325e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>004dac49-3a42-4810-baff-bb56f70cfd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg-firstName</value>
      <webElementGuid>cf529e3e-02b0-4a87-a93d-bd58373e98ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;register-page&quot;]/main[1]/div[@class=&quot;auth-container&quot;]/form[@id=&quot;registration-form&quot;]/input[@id=&quot;reg-firstName&quot;]</value>
      <webElementGuid>88d1d1ad-f3b5-4d9c-ba5a-1a72ea28e722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg-firstName']</value>
      <webElementGuid>40a9424b-cc9a-49f3-afac-f83d7f405231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration-form']/input</value>
      <webElementGuid>8a3efb65-4f98-48ea-9f11-a4dba778fcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8c0fd6b8-80a3-4dd0-8178-e2338e7da16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'reg-firstName']</value>
      <webElementGuid>7ac45f24-0ae2-4708-ab64-91bca5117b24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
