<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_reg-password</name>
   <tag></tag>
   <elementGuidId>e5730fcc-85c3-47dc-8077-53e0ab7e9443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reg-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Password&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24a7bf0c-491e-40cb-a2a1-a7f1ff9c80e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>92d691e8-5fff-49f2-b9ed-b89896f855ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg-password</value>
      <webElementGuid>9ba0e6df-8091-41de-9d96-48af3cb62e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&amp;])[A-Za-z\d@$!%*?&amp;]{8,}$</value>
      <webElementGuid>2de119a2-4fb8-4c0d-913d-c26b90c681ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Minimum 8 characters, at least one uppercase letter, one lowercase letter, one number, and one special character.</value>
      <webElementGuid>11ad6339-613c-4eaf-855a-217071f56979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;register-page&quot;]/main[1]/div[@class=&quot;auth-container&quot;]/form[@id=&quot;registration-form&quot;]/input[@id=&quot;reg-password&quot;]</value>
      <webElementGuid>b0890c6e-51c1-4d28-937c-29ab71c304a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg-password']</value>
      <webElementGuid>b7887565-b656-43a5-912d-25156513c3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration-form']/input[6]</value>
      <webElementGuid>1d710c3f-7f0a-467e-91b7-22ad82c4dc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>16a9632d-99bb-4719-b141-0121af77ba23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'reg-password' and @title = 'Minimum 8 characters, at least one uppercase letter, one lowercase letter, one number, and one special character.']</value>
      <webElementGuid>288fae60-e970-4042-8f4c-8c9feddd6ab1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
