<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_reg-username</name>
   <tag></tag>
   <elementGuidId>fd5940ca-5e95-4bc3-9d25-53d8e53eb402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reg-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reg-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Username&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8ed94e8-4a8c-4573-acdc-666665cf6457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8eb7f37-6331-43fc-bc25-9db2d3191b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reg-username</value>
      <webElementGuid>16af0f4c-5445-40c0-a1ad-d350b903ac7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;register-page&quot;]/main[1]/div[@class=&quot;auth-container&quot;]/form[@id=&quot;registration-form&quot;]/input[@id=&quot;reg-username&quot;]</value>
      <webElementGuid>2224a009-3f77-4110-881c-ecc7c9b49046</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reg-username']</value>
      <webElementGuid>93d1681a-9c6c-49de-9668-d644399dc7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration-form']/input[5]</value>
      <webElementGuid>8b099f6d-9eb6-4497-9e3a-cf636b61b32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>4cf3e43f-2356-4604-95d3-b2fcdf529263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'reg-username']</value>
      <webElementGuid>a76f5071-fb4d-4359-84b8-3301e4ec1970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
